### ISSUE TITLE
With canvas@1.2.10, renderCallback is never been called

### ISSUE THREAD

**Issue by SamyPesse** [yetzt/node-canvg#12]
`canvg` is not working with latest version of `node-canvas`, the `renderCallback` is never been called.

It'll probably be a good idea to add some unit tests to `canvg` to ensure that the module is correctly working with latest versions of `canvas` and `node.js`.

**Comment by yetzt** [comment]
tried it with `node-canvas@1.2.10`, cannot reproduce `renderCallback` not being called.
```
(require("./index.js"))((new (require("canvas"))()), '<svg height="100" width="100"><circle cx="50" cy="50" r="40" stroke="black" stroke-width="3" fill="red" /></svg>', { renderCallback: function(){ console.log("done"); }});
```
can you give me an example where it fails?
