### ISSUE TITLE
Failed at the canvas@1.3.12 install script 'node-gyp rebuild'

### ISSUE THREAD

**Issue by donnrri** [yetzt/node-canvg#13]
Hi

I cannot install the npm package

on 'npm install canvg --save'

I get 
Failed at the canvas@1.3.12 install script 'node-gyp rebuild'

Any ideas on how to solve this issue

**Comment by yetzt** [comment]
that's an issue with [canvas](https://github.com/Automattic/node-canvas), lollow their [install instructions](https://github.com/Automattic/node-canvas#installation) first. when this doesn't help, you should ask the for support.
